/**
 * Build `client.js`, the plain-script bundle the page loads.
 *
 * The bundle is hand-assembled rather than run through a bundler because it is a
 * single fixed-shaped artifact: a `window.__ModuleLoader__` script whose factory
 * `require`s only baseline modules the shell seeds (React and the UI primitives)
 * and inlines everything else. Three kinds of source are stitched together:
 *
 * 1. `client.source.js` — the authored client half, kept verbatim except that its
 *    imports become `require` calls, and the `// __WORKTIME_MODEL__` marker is
 *    replaced by (2).
 * 2. `holiday-source.js` and `worktime.js` — the pure model. Each is wrapped in a
 *    function that publishes its exports onto a shared `__modules` object, so the
 *    bundle never needs a module graph: imports are rewritten to destructuring, and
 *    the model's names are republished once at the factory top level for the client.
 * 3. `node_modules/chinese-days` — a self-contained CommonJS/UMD build with no
 *    ES-module entry. It is vendored verbatim and evaluated against a private scope,
 *    so its UMD wrapper produces a factory-scoped `chineseDays` binding and leaks
 *    nothing onto the page global.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";

const root = dirname(fileURLToPath(import.meta.url));
const require = createRequire(import.meta.url);
const marker = "// __WORKTIME_MODEL__";
const banner = "// Generated by build.mjs from client.source.js, worktime.js, holiday-source.js and chinese-days — do not edit directly.\n";

/** Model modules, in dependency order: each may call into the ones before it. */
const MODEL_MODULES = ["holiday-source.js", "worktime.js"];

/**
 * The object holding every inlined module, created up front so a module's wrapper
 * can be handed its siblings during initialization. Sibling slots exist (as
 * `undefined`) before any module runs, which is what keeps a cross-module import
 * out of a temporal dead zone; lookups go through the object rather than through
 * `const` bindings for the same reason.
 */
const MODULES_OBJECT = "__modules";

/** Specifiers the build resolves itself, so they never become `require` calls. */
const INLINED_SPECIFIERS = new Set(["./holiday-source.js", "chinese-days", "node:module"]);

/**
 * Node-only declarations the inlined model must not carry into the bundle.
 *
 * `import.meta` is a syntax error in a classic script, so this one is injected as
 * `importMetaUrl` instead; the build fails loudly if the line ever changes.
 */
const STRIPPED_DECLARATIONS = ["const importMetaUrl = import.meta.url;"];

/** Node-only names the inlined model reads, which the bundle supplies itself. */
const INJECTED = ["importMetaUrl", "createRequire"];

/**
 * The value each injected name receives inside the browser bundle.
 *
 * The model's `typeof` guard reads `createRequire` from the parameter rather than
 * from a global, and an empty URL keeps `createRequire(importMetaUrl)` from being
 * reached at all.
 */
const INJECTED_VALUES = { importMetaUrl: '""', createRequire: "undefined" };

/**
 * The scope constant a model module's exports are published under.
 * @param file - module basename, e.g. `worktime.js`.
 * @returns the constant name.
 */
function namespaceOf(file) {
	return `${file.replace(/\.js$/, "").replace(/\W/g, "_")}`;
}

/**
 * The factory-scope arguments passed to each inlined module wrapper.
 *
 * Sibling modules arrive through parameters rather than through the factory-scope
 * constants, because a module's own name would otherwise be shadowed by the local
 * `const` that publishes its exports. The injected values replace the two Node-only
 * imports.
 */
const WRAPPER_ARGS = ["chineseDays", ...INJECTED, ...MODEL_MODULES.map((file) => `sibling_${namespaceOf(file)}`)];
/**
 * The value bound to each wrapper parameter: the injected replacement where one
 * exists, otherwise the inlined-module slot for that sibling.
 * @returns one argument expression per wrapper parameter.
 */
function wrapperValues() {
	return WRAPPER_ARGS.map((name) => INJECTED_VALUES[name] ?? (name === "chineseDays" ? name : `${MODULES_OBJECT}.${name.replace(/^sibling_/, "")}`));
}

/**
 * Substitute text without letting `$` sequences in the replacement be read as
 * patterns (`$\`` would splice the rest of the file in). A function replacement
 * returns its string verbatim.
 * @param text - text to rewrite.
 * @param pattern - literal string or RegExp to find.
 * @param replacement - literal replacement text.
 * @returns the rewritten text.
 */
function substitute(text, pattern, replacement) {
	return text.replace(pattern, () => replacement);
}

/**
 * Drop the ESM `export { … };` statement from a module body.
 *
 * The name list is matched without `.` so a stray `export {` in a doc comment
 * cannot swallow the rest of the file.
 * @param source - module text.
 * @returns the body without its export statement.
 */
function stripExports(source) {
	return source.replace(/^[ \t]*export \{[^}]*\};[ \t]*$/m, "");
}

/**
 * Drop the `import … from "specifier";` lines the bundle satisfies inlined.
 *
 * Sibling model modules resolve through the wrapper arguments, and the vendored
 * package is bound before them, so an inlined import has nothing left to resolve.
 * @param source - module text.
 * @returns the body without its inlined imports.
 */
function stripInlinedImports(source) {
	return source
		.split("\n")
		.filter((line) => {
			if (STRIPPED_DECLARATIONS.includes(line.trim())) return false;
			const match = /^[ \t]*import\s+.+from\s+"([^"]+)";\s*$/.exec(line);
			if (match === null) return true;
			if (!INLINED_SPECIFIERS.has(match[1])) throw new Error(`unresolved import "${match[1]}" in an inlined module`);
			return false;
		})
		.join("\n");
}

/**
 * Wrap an inlined module in a function that publishes its exports, and run it.
 *
 * Every module is called with the same arguments, so cross-module imports and the
 * Node-only injections resolve without the build having to analyse which module
 * needs which. The wrapper's parameters satisfy the imports the build strips,
 * keeping each module's own top-level names out of the shared factory scope.
 *
 * Declaration and invocation stay adjacent, with the modules emitted in dependency
 * order: an importer reads its sibling's exports object only after that sibling has
 * run. That is also why the sibling parameters are `sibling_*` — a module's own name
 * would otherwise be shadowed by the local `const` publishing its exports.
 * @param file - module basename, e.g. `worktime.js`.
 * @returns the wrapper declaration followed by its invocation.
 */
function wrapModule(file) {
	const body = stripInlinedImports(stripExports(sources.get(file))).trim();
	const names = exportedNames(file);
	const namespace = namespaceOf(file);
	return [
		`${MODULES_OBJECT}.${namespace} = (function (${WRAPPER_ARGS.join(", ")}) {`,
		[importPrologue(file), indent(body, "\t")].filter(Boolean).join("\n"),
		`\treturn { ${names.join(", ")} };`,
		`})(${wrapperValues().join(", ")});`
	].join("\n");
}

/**
 * Bind a module's imports of the inlined model at the top of its wrapper.
 *
 * The imported names have to exist inside the importing body itself, because the
 * body calls them unqualified. The namespace stays a parameter rather than a
 * factory-scope constant so that a module is never shadowed by the `const` that
 * publishes its own exports.
 * @param file - module basename.
 * @returns the binding lines, or `""` when the module imports no sibling.
 */
function importPrologue(file) {
	return namedBindings(sources.get(file), (specifier) => `sibling_${namespaceOf(basename(specifier))}`).join("\n");
}

/**
 * Bind the model's public names at the factory's top level.
 *
 * `client.source.js` calls into the model directly, and the marker inlines the
 * model text into the same factory — but each module lives inside a wrapper
 * function, so its names have to be re-published for the client to see them. A name
 * exported by an earlier module wins, which is why the duplicates are filtered.
 * @returns one `const` destructuring statement per model module.
 */
function modelPublicBindings() {
	const seen = new Set();
	return MODEL_MODULES.flatMap((file) => {
		const names = exportedNames(file).filter((name) => !seen.has(name));
		for (const name of names) seen.add(name);
		return names.length === 0 ? [] : `const { ${names.join(", ")} } = ${MODULES_OBJECT}.${namespaceOf(file)};`;
	}).join("\n");
}

/**
 * Render `const { a, b } = <expr>;` for a source's relative (model) imports.
 * @param text - module text to scan.
 * @param namespaceFor - maps an import specifier to the expression holding its exports.
 * @returns one binding statement per import, indented for a wrapper body.
 */
function namedBindings(text, namespaceFor) {
	const lines = [];
	for (const match of text.matchAll(/^[ \t]*import\s+\{([^}]+)\}\s+from\s+"(\.\/[^"]+)";\s*$/gm)) {
		const names = match[1].split(",").map((name) => name.trim()).filter(Boolean);
		if (names.length === 0) continue;
		lines.push(`const { ${names.join(", ")} } = ${namespaceFor(match[2])};`);
	}
	return lines;
}

/**
 * Strip the `./` prefix and extension a relative import carries.
 * @param specifier - e.g. `./holiday-source.js`.
 * @returns the module basename, e.g. `holiday-source`.
 */
function basename(specifier) {
	return specifier.replace(/^\.\//, "").replace(/\.js$/, "");
}

/**
 * The names a model module's `export { … };` statement publishes.
 * @param file - module basename.
 * @returns the exported names, in declaration order.
 */
function exportedNames(file) {
	return [...sources.get(file).matchAll(/^[ \t]*export\s+\{([^}]*)\};\s*$/gm)]
		.flatMap((match) => match[1].split(",").map((name) => name.trim()).filter(Boolean));
}

/**
 * Indent every non-blank line, so wrapped module bodies read as nested source.
 * @param text - block to indent.
 * @param prefix - indentation to prepend.
 * @returns the indented block.
 */
function indent(text, prefix) {
	return text.split("\n").map((line) => (line === "" ? "" : `${prefix}${line}`)).join("\n");
}

/**
 * Probe which years the installed package ships arrangements for.
 *
 * The browser bundle cannot touch the filesystem, so the probe runs here and its
 * result is injected as a constant. This must stay in step with
 * `holiday-source.js`'s live Node probe; both read the package's per-year JSON.
 * @returns the sorted covered years.
 */
function probeCoveredYears() {
	const { main } = require("chinese-days/package.json");
	const dataDir = join(dirname(require.resolve("chinese-days")), "years");
	const years = [];
	const last = new Date().getUTCFullYear() + 6;
	for (let year = 2004; year <= last; year += 1) {
		try {
			require(join(dataDir, `${year}.json`));
			years.push(year);
		} catch {
			// The package does not ship this year's arrangement.
		}
	}
	if (years.length === 0) throw new Error(`chinese-days (${main}) ships no year data under ${dataDir}`);
	return years;
}

/**
 * The global branch of the vendored UMD header.
 *
 * The package's wrapper falls back to `globalThis` — which inside `new Function`
 * is the page's real global — so the branch is rewritten to a private scope
 * parameter. Vendoring the package must not leak a `chineseDays` global.
 */
const UMD_GLOBAL_BRANCH = 'typeof globalThis<"u"?globalThis:d||self';

/**
 * Vendor the `chinese-days` UMD build as a factory-scoped `chineseDays` binding.
 *
 * The package ships CommonJS/UMD only. It is evaluated with a private `this` and
 * with explicit `undefined` for the CommonJS and AMD hooks, so its wrapper takes
 * the global branch instead of exporting onto the loader's own `module`/`exports`.
 * That branch is then aimed at a private object rather than the page global; the
 * build fails loudly if a package bump changes the header.
 *
 * `new Function` is used because the package is a script, not an ES module. A page
 * CSP that forbids it is also the case in which the shell's own module loader
 * cannot run, so no separate fallback is warranted.
 * @returns the wrapper source plus the vendored version and size.
 */
function vendorChineseDays() {
	const entry = require.resolve("chinese-days");
	const { version } = require("chinese-days/package.json");
	const bundle = readFileSync(entry, "utf8");
	if (!bundle.includes(UMD_GLOBAL_BRANCH)) {
		throw new Error(`chinese-days@${version} changed its UMD header; update UMD_GLOBAL_BRANCH in build.mjs`);
	}
	const scoped = bundle.replace(UMD_GLOBAL_BRANCH, `(typeof __umdScope<"u"?__umdScope:0)||d||self`);
	const coveredYears = probeCoveredYears();
	const source = `
/* chinese-days@${version} — inlined UMD build; the model reads it through holiday-source.js. */
const chineseDays = (function () {
	const exported = {};
	new Function("module", "exports", "define", "__umdScope", ${JSON.stringify(scoped)})
		.call(exported, undefined, undefined, undefined, exported);
	if (typeof exported.chineseDays?.isWorkday !== "function") {
		throw new Error("chinese-days UMD build did not initialize");
	}
	return exported.chineseDays;
})();

/* The years the vendored package ships arrangements for, probed at build time:
   the browser bundle has no filesystem to probe, and a year the package does not
   cover must fall back to the fixed-date holidays rather than to a bare
   Monday–Friday test. */
const BROWSER_COVERED_YEARS = [${coveredYears.join(", ")}];
`;
	return { source, version, bytes: Buffer.byteLength(bundle), coveredYears };
}

const template = readFileSync(join(root, "client.source.js"), "utf8");
if (!template.includes(marker)) throw new Error(`client.source.js is missing the ${marker} marker`);

const sources = new Map(MODEL_MODULES.map((file) => [file, readFileSync(join(root, file), "utf8")]));
const vendored = vendorChineseDays();
const model = [
	`const ${MODULES_OBJECT} = {};`,
	vendored.source.trim(),
	...MODEL_MODULES.map((file) => wrapModule(file)),
	modelPublicBindings()
].join("\n\n");

/** Turn the template's ESM imports into `require` calls the loader can resolve. */
const withRequires = template.replace(/^import ([^;]+);$/gm, (statement, clause) => {
	const match = /^(\*\s+as\s+(\w+)|\{([^}]*)\})\s+from\s+"([^"]+)"$/.exec(clause.trim());
	if (match === null) return statement;
	const [, , namespace, named, specifier] = match;
	if (namespace !== undefined) return `const ${namespace} = require("${specifier}");`;
	return `const {${named}} = require("${specifier}");`;
});

const body = substitute(withRequires, /^[ \t]*export \{[^}]*\};[ \t]*$/m, "module.exports = { Ring, WorkHoursRing, apply, inject };");
// The model is spliced in last, and as literal text: it contains `$`-sequences.
const withModel = substitute(body, marker, model);

const bundle = [
	banner,
	"window.__ModuleLoader__.load({",
	'\tid: "@local/dsh-work-hours-ring",',
	"\tfactory(require) {",
	"\t\tconst module = { exports: {} };",
	"\t\tconst exports = module.exports;",
	withModel
		.split("\n")
		.map((line) => (line === "" ? "" : `\t\t${line}`))
		.join("\n"),
	"\t\treturn module.exports;",
	"\t}",
	"});",
	""
].join("\n");

writeFileSync(join(root, "client.js"), bundle);
process.stdout.write(`built client.js (${bundle.length} bytes, chinese-days@${vendored.version} inlined at ${vendored.bytes} bytes)\n`);
