import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = dirname(fileURLToPath(import.meta.url));
const marker = "// __WORKTIME_MODEL__";
const banner = "// Generated by build.mjs from client.source.js and worktime.js — do not edit directly.\n";

/**
 * Drop the ESM `export { … };` statement from a module body.
 * @param source - module text.
 * @returns the body without its export statement.
 */
function stripExports(source) {
	return source.replace(/^export \{[^}]*\};\s*$/m, "");
}

const template = readFileSync(join(root, "client.source.js"), "utf8");
if (!template.includes(marker)) throw new Error(`client.source.js is missing the ${marker} marker`);
const model = stripExports(readFileSync(join(root, "worktime.js"), "utf8")).trim();

const body = template
	.replace(/^import ([^;]+);$/gm, (statement, clause) => {
		const match = /^(\*\s+as\s+(\w+)|\{([^}]*)\})\s+from\s+"([^"]+)"$/.exec(clause.trim());
		if (match === null) return statement;
		const [, , namespace, named, specifier] = match;
		if (namespace !== undefined) return `const ${namespace} = require("${specifier}");`;
		return `const {${named}} = require("${specifier}");`;
	})
	.replace(/^export \{[^}]*\};\s*$/m, "module.exports = { Ring, WorkHoursRing, apply, inject };")
	// A function replacement keeps `$&`, `$'` and friends in the model literal.
	.replace(marker, () => model);

const bundle = [
	banner,
	"window.__ModuleLoader__.load({",
	'\tid: "@local/dsh-work-hours-ring",',
	"\tfactory(require) {",
	'\t\tconst module = { exports: {} };',
	"\t\tconst exports = module.exports;",
	body
		.split("\n")
		.map((line) => (line === "" ? "" : `\t\t${line}`))
		.join("\n"),
	"\t\treturn module.exports;",
	"\t}",
	"});",
	""
].join("\n");

writeFileSync(join(root, "client.js"), bundle);
process.stdout.write(`built client.js (${bundle.length} bytes)\n`);
