// Generated by build.mjs from client.source.js and worktime.js — do not edit directly.

window.__ModuleLoader__.load({
	id: "@local/dsh-work-hours-ring",
	factory(require) {
		const module = { exports: {} };
		const exports = module.exports;
		/**
		 * Authored source of the client half; `npm run build` inlines it into
		 * `client.js`, the browser bundle the page loads.
		 *
		 * The ring renders in `conversation.input.right`, the list slot the composer
		 * places immediately before the model selector, and recolors itself from the
		 * Beijing working-hours model:
		 *
		 * - orange while a working period is active,
		 * - blue while idle (weekends, holidays, lunch break, off hours).
		 *
		 * Hovering it shows how long is left until work ends, or when work starts next.
		 *
		 * @module client
		 */
		const React = require("react");
		const { Tooltip } = require("@deepseek-ai/dsh-client-ui-primitives");
		/**
		 * Pure Beijing-time ("北京时间", UTC+8) working-hours model.
		 *
		 * A working day is Monday–Friday that is not a Chinese statutory holiday. Its
		 * working periods are 09:00–12:00 and 14:00–18:00; every other instant is idle
		 * time — weekends, holidays, the lunch break, and the hours outside those two
		 * periods.
		 *
		 * @module worktime
		 */

		/** Beijing is UTC+8 with no daylight saving, so the offset is a constant. */
		const BEIJING_OFFSET_MINUTES = 8 * 60;

		/** Working periods of a working day, in minutes since Beijing midnight. */
		const WORK_PERIODS = [
			{ start: 9 * 60, end: 12 * 60 },
			{ start: 14 * 60, end: 18 * 60 }
		];

		/** Milliseconds in one Beijing day. */
		const DAY_MS = 24 * 60 * 60 * 1000;

		/**
		 * Off-weekday holiday windows, inclusive: the days the State Council actually
		 * grants off. Weekends are idle regardless, and makeup workdays (调休上班) fall
		 * on weekends, so they need no entry — under the requested rule a weekend is
		 * always idle.
		 *
		 * 2026 is the full 《国务院办公厅关于2026年部分节假日安排的通知》 (published
		 * 2025-11). Later years are not announced yet, so `fallbackHolidays()` covers
		 * their fixed-date holidays only; add `YYYY-MM-DD` rows here, or set
		 * `holidays` in the plugin config, once a year's notice is out.
		 */
		const HOLIDAYS = [
			// 2026 · 元旦
			"2026-01-01", "2026-01-02",
			// 2026 · 春节
			"2026-02-16", "2026-02-17", "2026-02-18", "2026-02-19", "2026-02-20", "2026-02-23",
			// 2026 · 清明节
			"2026-04-06",
			// 2026 · 劳动节
			"2026-05-01", "2026-05-04", "2026-05-05",
			// 2026 · 端午节
			"2026-06-19",
			// 2026 · 中秋节
			"2026-09-25",
			// 2026 · 国庆节 (10-01 … 10-08; 10-09 is the return-to-work Friday)
			"2026-10-01", "2026-10-02", "2026-10-05", "2026-10-06", "2026-10-07", "2026-10-08"
		];

		/** Per-year memo behind `fallbackHolidays`, keyed by four-digit year. */
		const FALLBACK_HOLIDAY_CACHE = new Map();

		/**
		 * Fixed-date statutory holidays for a year with no announcement yet: New Year's
		 * Day (1 day), Labour Day (3 days), and National Day (3 days).
		 *
		 * The keys are built once per year: `isWorkingDay` consults them for every
		 * candidate day a `nextWorkStart` search walks, so rebuilding the list per call
		 * would allocate hundreds of strings on every tick.
		 * @param year - four-digit Beijing year.
		 * @returns the memoized off-weekday date keys of that year.
		 */
		function fallbackHolidays(year) {
			let dates = FALLBACK_HOLIDAY_CACHE.get(year);
			if (dates === undefined) {
				const at = (month, day) => `${year}-${String(month).padStart(2, "0")}-${String(day).padStart(2, "0")}`;
				dates = new Set([at(1, 1), at(5, 1), at(5, 2), at(5, 3), at(10, 1), at(10, 2), at(10, 3)]);
				FALLBACK_HOLIDAY_CACHE.set(year, dates);
			}
			return dates;
		}

		/** Weekday labels for date text, indexed by `Date#getUTCDay`. */
		const WEEKDAY_LABELS = ["周日", "周一", "周二", "周三", "周四", "周五", "周六"];

		/**
		 * Normalize a calendar source into a lookup set.
		 * @param source - `{ holidays?: string[] }`; a missing list falls back to the
		 *   built-in `HOLIDAYS`.
		 * @returns the frozen calendar.
		 */
		function createCalendar(source) {
			return Object.freeze({ holidays: new Set(source?.holidays ?? HOLIDAYS) });
		}

		/** The built-in calendar, shared by every call that does not receive one. */
		const DEFAULT_CALENDAR = createCalendar();

		/**
		 * Read the Beijing wall clock for an instant.
		 * @param nowMs - epoch milliseconds.
		 * @returns Beijing calendar fields plus the minute of day.
		 */
		function beijingParts(nowMs) {
			const shifted = new Date(nowMs + BEIJING_OFFSET_MINUTES * 60_000);
			return {
				year: shifted.getUTCFullYear(),
				month: shifted.getUTCMonth() + 1,
				day: shifted.getUTCDate(),
				weekday: shifted.getUTCDay(),
				minuteOfDay: shifted.getUTCHours() * 60 + shifted.getUTCMinutes()
			};
		}

		/**
		 * Epoch milliseconds of a Beijing midnight, given an instant inside that day.
		 * @param nowMs - epoch milliseconds.
		 * @returns epoch milliseconds of 00:00 Beijing on that date.
		 */
		function beijingDayStart(nowMs) {
			const parts = beijingParts(nowMs);
			return Date.UTC(parts.year, parts.month - 1, parts.day) - BEIJING_OFFSET_MINUTES * 60_000;
		}

		/**
		 * Format a Beijing date as `YYYY-MM-DD`.
		 * @param parts - Beijing calendar fields.
		 * @returns the date key.
		 */
		function dateKey(parts) {
			return `${parts.year}-${String(parts.month).padStart(2, "0")}-${String(parts.day).padStart(2, "0")}`;
		}

		/**
		 * Test whether a Beijing date is a working day: Monday–Friday and not a holiday.
		 * @param parts - Beijing calendar fields.
		 * @param calendar - calendar lookup set.
		 * @returns true for a working day.
		 */
		function isWorkingDay(parts, calendar) {
			if (parts.weekday === 0 || parts.weekday === 6) return false;
			const key = dateKey(parts);
			return !calendar.holidays.has(key) && !fallbackHolidays(parts.year).has(key);
		}

		/**
		 * Test whether a Beijing minute of day falls inside a working period.
		 * @param minuteOfDay - minutes since Beijing midnight.
		 * @returns true inside 09:00–12:00 or 14:00–18:00.
		 */
		function inWorkPeriod(minuteOfDay) {
			return WORK_PERIODS.some((period) => minuteOfDay >= period.start && minuteOfDay < period.end);
		}

		/**
		 * Describe the working state at an instant.
		 * @param nowMs - epoch milliseconds; defaults to the current time.
		 * @param calendar - calendar lookup set; defaults to the built-in list.
		 * @returns `{ working, minuteOfDay, weekday }`.
		 */
		function stateAt(nowMs = Date.now(), calendar = DEFAULT_CALENDAR) {
			const parts = beijingParts(nowMs);
			const working = isWorkingDay(parts, calendar) && inWorkPeriod(parts.minuteOfDay);
			return { working, minuteOfDay: parts.minuteOfDay, weekday: parts.weekday };
		}

		/**
		 * Find the next instant work starts.
		 * @param nowMs - reference instant.
		 * @param calendar - calendar lookup set.
		 * @returns `{ atMs, sameDay }` — the next period start and whether it is still
		 *   the reference day in Beijing.
		 */
		function nextWorkStart(nowMs, calendar = DEFAULT_CALENDAR) {
			const today = beijingParts(nowMs);
			const dayStart = beijingDayStart(nowMs);
			for (let offset = 0; offset <= 370; offset += 1) {
				const start = dayStart + offset * DAY_MS;
				const parts = beijingParts(start + 60_000);
				if (!isWorkingDay(parts, calendar)) continue;
				for (const period of WORK_PERIODS) {
					if (offset === 0 && period.start <= today.minuteOfDay) continue;
					return { atMs: start + period.start * 60_000, sameDay: offset === 0 };
				}
			}
			/* v8 ignore next -- an unbounded search always finds a working day */
			return { atMs: nowMs, sameDay: false };
		}

		/**
		 * Find the next instant work ends.
		 * @param nowMs - reference instant inside a working period.
		 * @param calendar - calendar lookup set.
		 * @returns epoch milliseconds of the end of the current working period.
		 */
		function nextWorkEnd(nowMs, calendar = DEFAULT_CALENDAR) {
			const parts = beijingParts(nowMs);
			const period = WORK_PERIODS.find((candidate) => parts.minuteOfDay >= candidate.start && parts.minuteOfDay < candidate.end);
			/* v8 ignore next -- callers only ask while a working period is active */
			if (period === undefined) return nowMs;
			return beijingDayStart(nowMs) + period.end * 60_000;
		}

		/**
		 * Split a duration into whole hours and minutes.
		 * @param ms - non-negative duration in milliseconds.
		 * @returns `{ hours, minutes }`, with minutes rounded up so a remaining minute
		 *   never reads as `0h 0min`.
		 */
		function splitDuration(ms) {
			const totalMinutes = Math.max(0, Math.ceil(ms / 60_000));
			return { hours: Math.floor(totalMinutes / 60), minutes: totalMinutes % 60 };
		}

		/**
		 * Render a duration as `3h 12min`, dropping a zero hour or minute part.
		 * @param ms - non-negative duration in milliseconds.
		 * @returns the duration text.
		 */
		function durationText(ms) {
			const { hours, minutes } = splitDuration(ms);
			if (hours > 0 && minutes > 0) return `${hours}h ${minutes}min`;
			if (hours > 0) return `${hours}h`;
			return `${minutes}min`;
		}

		/**
		 * Render a Beijing date as `10月12日（周一）`.
		 * @param atMs - instant inside the day to render.
		 * @returns the date text.
		 */
		function dateText(atMs) {
			const parts = beijingParts(atMs);
			return `${parts.month}月${parts.day}日（${WEEKDAY_LABELS[parts.weekday]}）`;
		}

		/**
		 * Render a Beijing clock time as `09:00`.
		 * @param atMs - instant to render.
		 * @returns the clock text.
		 */
		function clockText(atMs) {
			const parts = beijingParts(atMs);
			return `${String(Math.floor(parts.minuteOfDay / 60)).padStart(2, "0")}:${String(parts.minuteOfDay % 60).padStart(2, "0")}`;
		}

		/**
		 * Build the ring's hover text for the current state.
		 *
		 * While a working period is active the text counts down to its end. While idle
		 * it counts up to the next start, dropping the date when that start is still
		 * today (before work or the lunch break) and naming it otherwise.
		 * @param nowMs - reference instant; defaults to the current time.
		 * @param calendar - calendar lookup set; defaults to the built-in list.
		 * @returns the tooltip text.
		 */
		function tooltipText(nowMs = Date.now(), calendar = DEFAULT_CALENDAR) {
			if (stateAt(nowMs, calendar).working) return `距离下班还有 ${durationText(nextWorkEnd(nowMs, calendar) - nowMs)}`;

			const next = nextWorkStart(nowMs, calendar);
			const remaining = durationText(next.atMs - nowMs);
			if (next.sameDay) return `距离上班还有 ${remaining}`;
			return `下次上班：${dateText(next.atMs)} ${clockText(next.atMs)}（还有 ${remaining}）`;
		}

		/** The slot the composer renders just before the model selector. */
		const SLOT_NAME = "conversation.input.right";

		/**
		 * Services this plugin mounts on. The Cordis loader refuses to hand a plugin a
		 * service it did not declare, so `ctx.slots` is unavailable without this export;
		 * shipped client plugins declare it the same way.
		 */
		const inject = ["slots"];

		/** Ring geometry, in CSS pixels. */
		const RING_EDGE = 16;
		const RING_CENTER = RING_EDGE / 2;
		/**
		 * Edge thickness. SVG strokes straddle the path, so the radius sheds half the
		 * stroke: `RING_RADIUS + RING_STROKE / 2` lands exactly on `RING_EDGE`, keeping
		 * the thick outer edge inside the 16px box the composer lays out.
		 */
		const RING_STROKE = 3.5;
		const RING_RADIUS = RING_CENTER - RING_STROKE / 2;

		/** Active-working color and idle color. */
		const WORKING_COLOR = "#f59e0b";
		const IDLE_COLOR = "#3b82f6";

		/** How often the ring re-reads the clock. */
		const TICK_MS = 30_000;

		/** Element id and keyframes name for the working pulse. */
		const STYLE_ID = "dsh-work-hours-ring-style";
		const PULSE_NAME = "dsh-work-hours-ring-pulse";

		/**
		 * Wrapper style. The wrapper must stay hit-testable: the host Tooltip attaches
		 * its pointer handlers to this element, and `pointer-events: none` on it or on
		 * the SVG would stop the hover text from ever opening.
		 */
		const ringStyle = {
			display: "inline-flex",
			alignItems: "center",
			justifyContent: "center",
			alignSelf: "center",
			width: RING_EDGE,
			height: RING_EDGE,
			flex: "0 0 auto",
			cursor: "default"
		};

		/**
		 * Build the ring artwork for a state.
		 *
		 * The artwork is a single stroked circle with a thick edge and no fill, so the
		 * middle stays hollow. It is the only shape, so the working pulse animates this
		 * stroke directly rather than a separate center dot.
		 *
		 * The host Tooltip clones its child and attaches both its pointer handlers and
		 * a `ref`; it measures the anchor through that ref, so a component that drops
		 * the ref makes the tooltip bail out at `getBoundingClientRect`. Forward it (and
		 * spread the cloned handlers) onto the wrapper element.
		 * @param props - cloned Tooltip props plus `working`, which selects the color
		 *   and the pulse.
		 * @param ref - the Tooltip's anchor ref.
		 * @returns the ring element.
		 */
		const Ring = React.forwardRef(function Ring({ working, ...rest }, ref) {
			const color = working ? WORKING_COLOR : IDLE_COLOR;
			return React.createElement(
				"span",
				{
					...rest,
					ref,
					style: { ...ringStyle, ...rest.style },
					"data-work-hours-state": working ? "working" : "idle"
				},
				React.createElement(
					"svg",
					{
						width: RING_EDGE,
						height: RING_EDGE,
						viewBox: `0 0 ${RING_EDGE} ${RING_EDGE}`,
						"aria-hidden": "true",
						focusable: "false",
						style: { display: "block", overflow: "visible" }
					},
					React.createElement("circle", {
						cx: RING_CENTER,
						cy: RING_CENTER,
						r: RING_RADIUS,
						fill: "none",
						stroke: color,
						strokeWidth: RING_STROKE,
						style: working ? { animation: `${PULSE_NAME} 2.4s ease-in-out infinite` } : undefined
					})
				)
			);
		});

		/**
		 * The ring plus its hover text, re-read on a fixed interval.
		 * @returns the tooltip-wrapped ring.
		 */
		function WorkHoursRing() {
			const calendar = React.useMemo(() => createCalendar(), []);
			const [nowMs, setNowMs] = React.useState(() => Date.now());

			React.useEffect(() => {
				const timer = setInterval(() => setNowMs(Date.now()), TICK_MS);
				return () => clearInterval(timer);
			}, []);

			const working = stateAt(nowMs, calendar).working;
			const text = tooltipText(nowMs, calendar);

			return React.createElement(
				Tooltip,
				{ label: text, side: "top", delayMs: 200, children: React.createElement(Ring, { working }) }
			);
		}

		/** Registration id inside the slot. */
		const ENTRY_ID = "work-hours-ring";

		/**
		 * Install the ring's keyframes once per document.
		 *
		 * The pulse fades the stroke instead of scaling it: CSS transforms on an SVG
		 * shape resolve `transform-origin` against the viewBox, so a scale would drift
		 * the ring toward the box corner rather than breathing about its own center.
		 * @returns a disposer that removes the style element.
		 */
		function installStyle() {
			if (document.getElementById(STYLE_ID) !== null) return () => {};
			const style = document.createElement("style");
			style.id = STYLE_ID;
			style.setAttribute("data-plugin", ENTRY_ID);
			style.textContent = [
				`@keyframes ${PULSE_NAME} {`,
				"  0%, 100% { opacity: 1; }",
				"  50% { opacity: 0.3; }",
				"}",
				"@media (prefers-reduced-motion: reduce) {",
				`  [data-work-hours-state="working"] circle { animation: none !important; }`,
				"}"
			].join("\n");
			document.head.append(style);
			return () => style.remove();
		}

		/**
		 * Register the ring in the composer's trailing list.
		 *
		 * The module-level `inject` beside this export is required: the Cordis loader
		 * refuses to hand a plugin a service it did not declare, so `ctx.slots` throws
		 * "cannot get property \"slots\" without inject" and the whole page fails its
		 * boot audit without it.
		 * @param ctx - client root context.
		 */
		function apply(ctx) {
			ctx.effect(() => installStyle(), "work-hours-ring: keyframes");
			ctx.slots.inject(SLOT_NAME, () =>
				ctx.slots.register(
					{
						name: SLOT_NAME,
						id: ENTRY_ID,
						order: 100,
						inject: () => ({})
					},
					WorkHoursRing
				)
			);
		}

		module.exports = { Ring, WorkHoursRing, apply, inject };
		return module.exports;
	}
});
